### ISSUE TITLE
Running trubar with trailing slashes causes missing first letters

### ISSUE THREAD

**Issue by ajdapretnar** [janezd/trubar#30]
I ran `trubar translate orange-translations/orange3/si.yaml -s orange3/ -d orangeSI/` to integrate translations into source code. What happened is all non-hidden files were missing the first letter of the file name.

**Comment by janezd** [comment]
The hidden miss the first letter as well, I believe. Hidden files are hidden because they start with `.`, which was removed, I suppose. :)
